
pub const ImageDataDirectory = extern struct {
    virtual_address: u32,
    size: u32,
};

pub const ImageOptionalHeader64 = extern struct {
    magic: u16,
    major_linker_ver: u8,
    minor_linker_ver: u8,
    size_of_code: u32,
    size_of_init_data: u32,
    size_of_uninit_data: u32,
    entry_point_rva: u32,
    base_of_code: u32,
    image_base: u64,
    section_alignment: u32,
    file_alignment: u32,
    major_os_ver: u16,
    minor_os_ver: u16,
    major_image_ver: u16,
    minor_image_ver: u16,
    major_subsys_ver: u16,
    minor_subsys_ver: u16,
    win32_version: u32,
    size_of_image: u32,
    size_of_headers: u32,
    checksum: u32,
    subsystem: u16,
    dll_characteristics: u16,
    size_of_stack_reserve: u64,
    size_of_stack_commit: u64,
    size_of_heap_reserve: u64,
    size_of_heap_commit: u64,
    loader_flags: u32,
    number_of_directories: u32,
    directories: [16]ImageDataDirectory,
};
